language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-21
    - android-24
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 60
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest --info
